GET http://localhost:3000/tags

###

POST http://localhost:3000/tags HTTP/1.1
Content-Type: application/json

{
    "content": "klwejfoiqwejfiqjwef;oiqwejfoiqwejf",
    "title": "ay btengan",
    "slug": "j0f91834jf09834jf934"
}

###

DELETE http://localhost:3000/tags/1

###

PUT http://localhost:3000/tags/2
Content-Type: application/json

{
    "title": "ay felfel",
    "slug": "jj392fj034jf994",
    "content": "owjfpoiqjwepfoiqjwefpoiqjewfpoij"
}

