GET http://localhost:3000/products

###

POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
    "name": "toast",
    "unit_type": "item",
    "price": 18,
    "stock": 20
}

###

DELETE http://localhost:3000/products/6085f5fe0bc13b2559bf07e8

###

PUT http://localhost:3000/products/6085f701254a39260f24d3f5
Content-Type: application/json

{
    "name": "chocolate",
    "unit_type": "item",
    "price": 20,
    "stock": 20
}

